install driver first step

diff --git a/usr/sbin/nvidia-privative-drivers-install b/usr/sbin/nvidia-privative-drivers-install
--- a/usr/sbin/nvidia-privative-drivers-install
+++ b/usr/sbin/nvidia-privative-drivers-install
@@ -230,11 +230,6 @@ interactive_ask_privative(){
     local ret
     el_debug
 
-    local message_title
-    message_title="$( printf "$( eval_gettext "Nvidia Graphic Card" )" "" )"
-    local message_message
-    message_message="$( printf "$( eval_gettext "Do you want to install the privative drivers of nvidia? We suggest to use them to have a better experience, it offers 3D acceleration and other features like a smoother desktop, they are also most of the times more stable than the free driver." )" "" )"
-
 
     # }}}
     # ask if want to install the privative one or the free {{{
@@ -244,22 +239,26 @@ interactive_ask_privative(){
 
         if ((is_mode_live)) ; then
             # TODO: deleteme in the future (request feedback experience) {{{
-            if el_check_version_development "20" ; then
+            if el_check_version_development "20" && ! ((is_mode_auto)) ;  then
                 local message_report_experience
-                message_report_experience="$( printf "$( eval_gettext "You have a Nvidia card! We are just finishing the feature to install the privative drivers in both live and installed mode, could be extremely helpful for us if you simply enter later in our chat to tell us if there's anything that didn't worked with them, you can tell us suggestions too, can you connect later and just say something like Nvidia Driver Version Number worked fine? You can found the chat from the second icon of your dock or online from the website. Thank you!" )" "" )"
+                message_report_experience="$( printf "$( eval_gettext "You have a Nvidia card! We are just finishing the feature to install the privative drivers (in both live and installed mode), could be extremely helpful for us if you simply enter in our chat to tell us if there's anything that didn't worked with them or any suggestion. Just say something like Nvidia Driver Version Number worked fine. You can found the chat from the second icon of your dock or online from the website. Thank you!" )" "" )"
 
-                if ! dialog --timeout 90 --clear --colors --backtitle "Elive Systems" \
+                if ! dialog --timeout 80 --clear --colors --backtitle "Elive Systems" \
                     --title "Yeppeeeeee! New features!" \
                     --yesno "$message_report_experience" \
                     0 0  ; then
 
                     clear
+                    echo
                     log_progress_msg "Bad boy... spank spank!"
                     sleep 3
-                    log_progress_msg "Now im upset and im going to make you wait... forever forver"
-                    sleep 4
-                    log_progress_msg "Ok, was a joke :P continuing..."
-                    sleep 2
+                    echo
+                    log_progress_msg "Now im upset and im going to make you wait... forever forever!"
+                    sleep 5
+                    echo
+                    log_progress_msg "Ok, that was a bad joke :P continuing..."
+                    sleep 3
+                    echo
                 fi
 
             fi
@@ -271,7 +270,12 @@ interactive_ask_privative(){
             if ((is_mode_auto)) ; then
                 ret=0
             else
-                dialog --timeout 90 --clear --colors --backtitle "Elive Systems" \
+                local message_title
+                message_title="$( printf "$( eval_gettext "Nvidia Graphic Card" )" "" )"
+                local message_message
+                message_message="$( printf "$( eval_gettext "Do you want to install the privative drivers of Nvidia? We suggest to use them to have a better experience, it offers 3D acceleration and other features like a smoother desktop, they are also most of the times more stable than the free driver." )" "" )"
+
+                dialog --timeout 60 --clear --colors --backtitle "Elive Systems" \
                     --title "$message_title" \
                     --yesno "$message_message" \
                     0 0
@@ -337,6 +341,8 @@ interactive_ask_driver_version(){
             case $_id in
                 *nvidia|current)
                     _desc="$( printf "$( eval_gettext "Last driver for the most newest cards" )" )"
+                    # show the specific version, its always good to know "what" exactly is considered the last version to know if its really supported on your hardware or not
+                    _desc="$_desc ($( apt-cache show xserver-xorg-video-nvidia | grep "^Version: " | awk '{print $2}' | sort -V | tail -1 | sed -e 's|-.*$||g' ))"
                     ;;
                 *legacy-304xx)
                     _desc="$( printf "$( eval_gettext "Previously last driver for recent cards" )" )"
@@ -370,7 +376,7 @@ interactive_ask_driver_version(){
             fi
 
         done 3<<< "$( { echo "current" ;  apt-cache search xserver-xorg-video-nvidia | grep -v "nouveau" | awk '{print $1}' | sort -V -r ; } )" \
-            | xargs dialog --timeout 120 --radiolist "$message_select_driver" 0 0 0  2>"/tmp/.$(basename $0)-ret"
+            | xargs dialog --timeout 80 --clear --colors --backtitle "Elive Systems" --radiolist "$message_select_driver" 0 0 0  2>"/tmp/.$(basename $0)-ret"
 
         # get result
         ret="$( cat "/tmp/.$(basename $0)-ret" | head -1 )"
@@ -380,10 +386,12 @@ interactive_ask_driver_version(){
         read -r ret <<< "$ret"
 
         # update / force the version to use
-        _NVIDIA_VERSION="$ret"
+        if [[ -n "$ret" ]] ; then
+            _NVIDIA_VERSION="$ret"
+        fi
 
         if ((is_mode_live)) ; then
-            log_progress_msg "Using the '$ret' nvidia driver version"
+            log_progress_msg "Using the '$_NVIDIA_VERSION' nvidia driver version"
             sleep 1
         else
             el_debug "Nvidia version was '$_NVIDIA_VERSION' and now is '$ret'"
@@ -403,11 +411,69 @@ interactive_ask_driver_version(){
             ;;
     esac
 
-    el_explain 2 "Selected list of pacakges to install:\n__$( echo "${_NVIDIA_PACKAGES}" | tr ' ' '\n' )__"
+    el_explain 2 "Selected list of packages to install:\n__$( echo "${_NVIDIA_PACKAGES}" | tr ' ' '\n' )__"
 
 
     # - select packages to install depending on which version we selected }}}
 
+
+}
+
+#===  FUNCTION  ================================================================
+#          NAME:  install_driver
+#   DESCRIPTION:  prepare system and install the driver to use nvidia
+#    PARAMETERS:  -
+#       RETURNS:  -
+#===============================================================================
+install_driver(){
+    # pre {{{
+    el_debug
+
+    if ! el_check_variables "_NVIDIA_VERSION" ; then
+        el_error "We don't know which version of nvidia to use"
+        exit 1
+    fi
+
+    if ! el_check_variables "_NVIDIA_PACKAGES" ; then
+        el_error "We don't know which packages of nvidia to install"
+        exit 1
+    fi
+
+    # }}}
+
+    # prepare system (put xorg.conf first to not have a dialog to appear)
+     
+    # we don't really need this if we skip the need to, so its by default a good thing to ask the user
+    #export DEBIAN_FRONTEND="noninteractive"
+    # TODO: put xorg.conf first
+
+    if ! apt-get install -y $_NVIDIA_PACKAGES ; then
+        el_aptget_update
+
+        if ! apt-get install -y $_NVIDIA_PACKAGES ; then
+            el_aptget_update force
+
+            if ! apt-get install -y $_NVIDIA_PACKAGES ; then
+                while read -ru 3 package
+                do
+                    if ! apt-get install -y $package ; then
+                        echo -e "\nE: Installing nvidia packages failed, please report the previous error messages to Elive" 1>&2
+                        sleep 20
+                    fi
+                done 3<<< "$( echo "$_NVIDIA_PACKAGES")"
+            fi
+        fi
+    fi
+
+    if which nvidia-modprobe 1>/dev/null 2>&1 ; then
+        nvidia-modprobe
+    else
+        # TODO: what about ohter verisons?
+        modprobe nvidia
+    fi
+
+    # reload devices just in case
+    service nvidia-kernel restart 1>/dev/null 2>&1
 
 
 }
@@ -481,6 +547,7 @@ main(){
     interactive_ask_privative
     detect_driver_version
     interactive_ask_driver_version
+    installing_driver
 
 
 }
