multiple improvements

diff --git a/usr/sbin/nvidia-privative-drivers-install b/usr/sbin/nvidia-privative-drivers-install
--- a/usr/sbin/nvidia-privative-drivers-install
+++ b/usr/sbin/nvidia-privative-drivers-install
@@ -69,7 +69,9 @@ load_driver(){
     # load driver
     if which nvidia-modprobe 1>/dev/null 2>&1 ; then
         nvidia-modprobe
-    else
+    fi
+
+    if ! lsmod | grep -qs nvidia ; then
         nvidia_modules="$( find /lib/modules -type f -iname nvidia'*'ko | psort --  -p "nvidia-legacy-${_NVIDIA_VERSION}.ko" -p "${_NVIDIA_VERSION}.ko" | grep -vE "(uvm|modeset|drm).ko" )"
 
         if [[ "$( echo "$nvidia_modules" | wc -l )" -ge 1 ]] ; then
@@ -876,39 +878,36 @@ install_driver(){
     load_driver
 
     if ! lsmod | grep -qs nvidia ; then
-        sleep 6
-        local message_unable_to_load
+        if ! ((is_mode_auto)) ; then
+            local message_unable_to_load
 
-        # default message for not working drivers
-        if ! lsmod | grep -qs nvidia ; then
-            NOREPORTS=1 el_error "Unable to load NVIDIA module"
-            sleep 2
+            # default message for not working drivers
+            if ! lsmod | grep -qs nvidia ; then
+                NOREPORTS=1 el_error "Unable to load NVIDIA module"
 
-            message_unable_to_load="$( printf "$( eval_gettext "Elive was unable to load the NVIDIA module. Reasons may be the compilation has failed, the device is busy, or the device was not found. We suggest a reboot and select a different kernel version. If the video card is old then an older version of the NVIDIA driver will be require from an older kernel." )" "" )"
+                message_unable_to_load="$( printf "$( eval_gettext "Elive was unable to load the NVIDIA module. Reasons may be the compilation has failed, the device is busy, or the device was not found. We suggest a reboot and select a different kernel version. If the video card is old then an older version of the NVIDIA driver will be require from an older kernel." )" "" )"
+            fi
+
+
+            if modprobe $_NVIDIA_MODULE 2>&1 | grep -aqsE "(No supported display adapters|No such device)" || dmesg 2>&1 | colors-remove | grep -aqsi "No NVIDIA graphics adapter found" ; then
+                message_unable_to_load="$( printf "$( eval_gettext "Error: The compiled drivers don't looks like to accept your model of graphic card, you could try to compile the other versions too and if no works, just try to use the Free-drivers." )" "" )"
+
+            fi
+
+            # module simply was not compiled
+            if ! find "/lib/modules/$(uname -r)" -type f -iname '*'nvidia'*' | grep -qs "nvidia" ; then
+                message_unable_to_load="$( printf "$( eval_gettext "Error: The driver has not compiled successfully, this normally happens when you have a too much recent kernel, or too old, try to reboot and select to use a different kernel version from the boot selector list. We suggest to use the Free-drivers if they works for you." )" "" )"
+            fi
+
+
+            # show the message if we have any
+            if [[ -n "$message_unable_to_load" ]] && ! ((is_mode_auto)) ; then
+                dialog --timeout 280 --clear --colors --backtitle "Elive Systems: Use Ctrl-L to redraw, Enter to confirm" \
+                    --title "Unable to load module" \
+                    --msgbox "$message_unable_to_load" \
+                    0 0
+            fi
         fi
-
-
-        if modprobe $_NVIDIA_MODULE 2>&1 | grep -qs "No supported display adapters" ; then
-            sleep 4
-            message_unable_to_load="$( printf "$( eval_gettext "Error: The compiled drivers don't looks like to accept your model of graphic card, you could try to compile the other versions too and if no works, just try to use the Free-drivers." )" "" )"
-
-        fi
-
-        # module simply was not compiled
-        if ! find "/lib/modules/$(uname -r)" -type f -iname '*'nvidia'*' | grep -qs "nvidia" ; then
-            sleep 4
-            message_unable_to_load="$( printf "$( eval_gettext "Error: The driver has not compiled successfully, this normally happens when you have a too much recent kernel, or too old, try to reboot and select to use a different kernel version from the boot selector list. We suggest to use the Free-drivers if they works for you." )" "" )"
-        fi
-
-
-        # show the message if we have any
-        if [[ -n "$message_unable_to_load" ]] && ! ((is_mode_auto)) ; then
-            dialog --timeout 280 --clear --colors --backtitle "Elive Systems: Use Ctrl-L to redraw, Enter to confirm" \
-                --title "Unable to load module" \
-                --msgbox "$message_unable_to_load" \
-                0 0
-        fi
-
 
 
         # cleanups
@@ -917,7 +916,7 @@ install_driver(){
             try_again
             #NOREPORTS=1 el_warning "Switched to the default drivers option"
             #sleep 4
-            exit 0
+            #exit 0
         fi
     fi
 
