this should be a pretty good version

diff --git a/usr/sbin/nvidia-privative-drivers-install b/usr/sbin/nvidia-privative-drivers-install
--- a/usr/sbin/nvidia-privative-drivers-install
+++ b/usr/sbin/nvidia-privative-drivers-install
@@ -26,7 +26,7 @@ usage(){
     echo -e "  -m: model (version of driver) to use"
     echo -e "      - like:  current, legacy-304xx, legacy-173xx, legacy-96xx, legacy-71xx"
     #echo -e "  -s: simulate mode (simulate that you have the specified model hardware" # TODO
-    #echo -e "  -u: uninstall driver"
+    echo -e "  -u: uninstall driver"
     echo -e "  -v: verbose mode"
 }
 
@@ -241,7 +241,7 @@ interactive_ask_privative(){
             # TODO: deleteme in the future (request feedback experience) {{{
             if el_check_version_development "20" && ! ((is_mode_auto)) ;  then
                 local message_report_experience
-                message_report_experience="$( printf "$( eval_gettext "You have a Nvidia card! We are just finishing the feature to install the privative drivers (in both live and installed mode), could be extremely helpful for us if you simply enter in our chat to tell us if there's anything that didn't worked with them or any suggestion. Just say something like Nvidia Driver Version Number worked fine. You can found the chat from the second icon of your dock or online from the website. Thank you!" )" "" )"
+                message_report_experience="$( printf "$( eval_gettext "We are just finishing the feature to install the privative Nvidia drivers (in both live and installed mode), could be extremely helpful for us if you simply enter in our chat to tell us if there's anything that didn't worked with them or any suggestion. Just say something like Nvidia Driver Version Number worked fine. You can found the chat from the second icon of your dock or online from the website. Thank you!" )" "" )"
 
                 if ! dialog --timeout 80 --clear --colors --backtitle "Elive Systems" \
                     --title "Yeppeeeeee! New features!" \
@@ -385,16 +385,16 @@ interactive_ask_driver_version(){
         # remove extra leading blank chars
         read -r ret <<< "$ret"
 
+        log_progress_msg "Using the '$ret' nvidia driver version"
+
+        # add a pause in case we selected a different than the expected one
+        if [[ "${ret}" != "$_NVIDIA_VERSION" ]] ; then
+            sleep 3
+        fi
+
         # update / force the version to use
         if [[ -n "$ret" ]] ; then
             _NVIDIA_VERSION="$ret"
-        fi
-
-        if ((is_mode_live)) ; then
-            log_progress_msg "Using the '$_NVIDIA_VERSION' nvidia driver version"
-            sleep 1
-        else
-            el_debug "Nvidia version was '$_NVIDIA_VERSION' and now is '$ret'"
         fi
 
     fi
@@ -404,10 +404,14 @@ interactive_ask_driver_version(){
     # select packages to install depending on which version we selected {{{
     case $_NVIDIA_VERSION in
         current)
-            _NVIDIA_PACKAGES="nvidia-driver nvidia-glx nvidia-settings"
+            _NVIDIA_PACKAGES="nvidia-driver nvidia-settings"
             ;;
         *)
-            _NVIDIA_PACKAGES="nvidia-driver-$_NVIDIA_VERSION nvidia-glx-$_NVIDIA_VERSION nvidia-settings-$_NVIDIA_VERSION"
+            if apt-cache search "nvidia-settings-$_NVIDIA_VERSION" | awk '{print $1}' | grep -qs "nvidia-settings-$_NVIDIA_VERSION" ; then
+                _NVIDIA_PACKAGES="nvidia-$_NVIDIA_VERSION-driver nvidia-settings-$_NVIDIA_VERSION"
+            else
+                _NVIDIA_PACKAGES="nvidia-$_NVIDIA_VERSION-driver"
+            fi
             ;;
     esac
 
@@ -439,13 +443,44 @@ install_driver(){
         exit 1
     fi
 
+    mkdir -p /etc/X11/xorg.conf.d
+
+
     # }}}
 
-    # prepare system (put xorg.conf first to not have a dialog to appear)
-     
+    # TODO: check the debian and archlinux wiki's to see if we lack anything
+
+    # create conf first
+    if [[ -s "/usr/share/live/config/xserver-xorg/nvidia.conf" ]] ; then
+        cp "/usr/share/live/config/xserver-xorg/nvidia.conf" /etc/X11/xorg.conf.d/
+    else
+        # generate a dummy template
+        : > /etc/X11/xorg.conf.d/nvidia.conf
+
+        echo 'Section "Device"' >> /etc/X11/xorg.conf.d/nvidia.conf
+        echo '        Identifier     "Default screen"' >> /etc/X11/xorg.conf.d/nvidia.conf
+        echo '        Driver         "nvidia"' >> /etc/X11/xorg.conf.d/nvidia.conf
+        echo '        Option         "NoLogo"     "true"' >> /etc/X11/xorg.conf.d/nvidia.conf
+        echo 'EndSection' >> /etc/X11/xorg.conf.d/nvidia.conf
+
+    fi
+
+    # install !
     # we don't really need this if we skip the need to, so its by default a good thing to ask the user
     #export DEBIAN_FRONTEND="noninteractive"
-    # TODO: put xorg.conf first
+    # note: we should have already enough memory because we should have already requested to add a swap in case that we don't have enough space
+    # FIXME: needs to be better: if
+    if lsmod | grep -qs nouveau ; then
+        if ((is_mode_force)) ; then
+            rmmod -f nouveau
+        else
+            rmmod nouveau
+            if lsmod | grep -qs nouveau ; then
+                echo -e "\nE: nouveau module is loaded and we cannot unload it"
+                echo -e "You should reboot and add the boot parameter 'modprobe.blacklist=nouveau' to tell the kernel to not load it, or you can use the -f option (but it can make your screen unreadable, which is ok if you are running it from a ssh)"
+            fi
+        fi
+    fi
 
     if ! apt-get install -y $_NVIDIA_PACKAGES ; then
         el_aptget_update
@@ -465,6 +500,8 @@ install_driver(){
         fi
     fi
 
+
+    # load driver
     if which nvidia-modprobe 1>/dev/null 2>&1 ; then
         nvidia-modprobe
     else
@@ -472,10 +509,94 @@ install_driver(){
         modprobe nvidia
     fi
 
+    if ! lsmod | grep -qs nvidia ; then
+        el_error "Unable to load NVIDIA module"
+        exit 1
+    fi
+
     # reload devices just in case
     service nvidia-kernel restart 1>/dev/null 2>&1
 
+    el_explain 2 "Install complete"
 
+}
+
+#===  FUNCTION  ================================================================
+#          NAME:  uninstall_driver
+#   DESCRIPTION:  uninstalls any possible nvidia drivers and make the system work back on nouveau
+#    PARAMETERS:  -
+#       RETURNS:  -
+#===============================================================================
+uninstall_driver(){
+    # pre {{{
+    local line
+    el_debug
+
+    unset _NVIDIA_PACKAGES
+
+    # }}}
+
+    # unload module first
+    if lsmod | grep -qs nvidia ; then
+        rmmod nvidia
+
+        if lsmod | grep -qs nvidia ; then
+            if ((is_mode_force)) ; then
+                rmmod -f nvidia
+            else
+                el_explain 0 "E: unable to unload the __nvidia module__, if you are running the graphical system you should exit from it first, and if is not the case and you want to force to proceed use the -f option"
+                exit 1
+            fi
+        fi
+    fi
+
+
+    # remove any possible xorg conf (before uninstall packages)
+    rm -f /etc/X11/xorg.conf.d/nvidia.conf 2>/dev/null
+
+
+    # remove all nvidia packages
+    while read -ru 3 line
+    do
+        [[ -z "$line" ]] && continue
+
+        # if matches
+        if echo "$line" | grep -qsE "(nvidia|lib.*nvidia|glx.*nvidia|xserver.*nvidia)" ; then
+            # which doesn't maches
+            if ! echo "$line" | grep -qsE "(nvidia-detect|glx-alternative-nvidia|glx-diversions)" ; then
+                el_debug "Adding $line to the list of uninstall packages"
+                _NVIDIA_PACKAGES="$_NVIDIA_PACKAGES $line"
+            fi
+        fi
+
+    done 3<<< "$( dpkg -l | grep nvidia | awk '{print $2}' )"
+
+    # remove extra leading blank chars
+    read -r _NVIDIA_PACKAGES <<< "$_NVIDIA_PACKAGES"
+
+    if [[ -n "$_NVIDIA_PACKAGES" ]] ; then
+        if ((is_mode_auto)) ; then
+            el_debug "apt-get remove --purge -y $_NVIDIA_PACKAGES"
+            DEBIAN_FRONTEND="noninteractive" apt-get remove --purge -y $_NVIDIA_PACKAGES
+        else
+            el_debug "apt-get remove --purge $_NVIDIA_PACKAGES"
+            apt-get remove --purge $_NVIDIA_PACKAGES
+        fi
+    else
+        el_warning "We wanted to uninstall packages but none were found, already removed?"
+    fi
+
+    # show final result
+    if dpkg -l | grep nvidia | awk '{print $2}' | grep -qs nvidia ; then
+        echo -e ""
+        el_error "We still having some nvidia packages not uninstalled:"
+        dpkg -l | grep nvidia | awk '{print $2}' | grep nvidia  1>&2
+    else
+        el_explain 0 "Driver NVIDIA uninstalled __successfully__"
+    fi
+
+    # we have nothing more to do so exit
+    exit
 }
 
 
@@ -525,10 +646,9 @@ main(){
                 export EL_DEBUG=0
 
                 ;;
-            #u)
-                #check_hardware
-                #uninstall_driver
-                #;;
+            u)
+                is_mode_uninstall=1
+                ;;
             \?)
                 el_error "Invalid option: -$OPTARG"
                 usage
@@ -543,11 +663,17 @@ main(){
     done
 
 
+    # i dont like very much this flow here, but were it must be? in each called functions with a return in the pre ? mmh... what is the good coding practices for this case?
+    if ((is_mode_uninstall)) ; then
+        check_hardware
+        uninstall_driver
+    fi
+
     check_hardware
     interactive_ask_privative
     detect_driver_version
     interactive_ask_driver_version
-    installing_driver
+    install_driver
 
 
 }
