refactoring

diff --git a/usr/sbin/user-manager b/usr/sbin/user-manager
--- a/usr/sbin/user-manager
+++ b/usr/sbin/user-manager
@@ -27,6 +27,9 @@ if [ -z "$USERS_GID" ]; then
     USERS_GID=100
 fi
 
+trap "exit_ok" EXIT
+trap "exit_error" 1 3 5 6 14 15 ERR TERM
+
 
 guitool=zenity
 temp_error="/tmp/$(basename $0)-${USER}-$$"
@@ -35,10 +38,16 @@ el_dependencies_check "${guitool},chpasswd,debconf-get-selections,grep,groupadd,
 
 ###########################################################################
 exit_error(){
-    $guitool --error --text="Error, $( cat "${temp_error}" )"
+    if [[ -s "$temp_error" ]] ; then
+        $guitool --error --text="Error, $( cat "${temp_error}" )"
+    else
+        $guitool --error
+    fi
 
+    exit
+}
+exit_ok(){
     rm -f "${temp_error}" 2>/dev/null
-    exit 1
 }
 
 ###########################################################################
@@ -145,16 +154,16 @@ user_add(){
     if [[ "$USERGROUPS" = "yes" ]] ; then
         USERGROUP="$username"
         # do not create it or adduser will fail
-        #groupadd $USERGROUP 2>"${temp_error}" || exit_error
+        #groupadd $USERGROUP 2>"${temp_error}" || exit 1
     else
         USERGROUP="$USERS_GID"
     fi
 
     # create user
-    #$USERADD -d "$DHOME/$username" -m -k /etc/skel -c "Elive User" -g "$USERGROUP" -s /bin/bash "$username" 2>"${temp_error}" || exit_error
-    #$USERADD -m $username 2>/tmp/.errormessage || exit_error
-    #$ADDUSER --force-badname --disabled-password --gecos 'Elive User' --shell /bin/zsh "$username" 2>/tmp/.errormessage || exit_error
-    #$ADDUSER --force-badname --disabled-password --gecos 'Elive User' --shell /bin/zsh "$username" 2>/tmp/.errormessage || exit_error
+    #$USERADD -d "$DHOME/$username" -m -k /etc/skel -c "Elive User" -g "$USERGROUP" -s /bin/bash "$username" 2>"${temp_error}" || exit 1
+    #$USERADD -m $username 2>/tmp/.errormessage || exit 1
+    #$ADDUSER --force-badname --disabled-password --gecos 'Elive User' --shell /bin/zsh "$username" 2>/tmp/.errormessage || exit 1
+    #$ADDUSER --force-badname --disabled-password --gecos 'Elive User' --shell /bin/zsh "$username" 2>/tmp/.errormessage || exit 1
     # update: adduser doesn't accepts names like Владимир
     useradd -c "Elive User" -m -s "/bin/zsh" "$username"
     # create / fix the files too
@@ -170,7 +179,7 @@ user_add(){
     #echo "$username:$userpass" | chpasswd $chpassopt
     bash -c 'printf "%s:%s\\n" "$1" "$2" | chpasswd -m' -- "$username" "$userpass"
 
-    #elive-skel user $username $USERGROUP 2>"${temp_error}" || exit_error
+    #elive-skel user $username $USERGROUP 2>"${temp_error}" || exit 1
 
     groups_add
 
@@ -243,9 +252,9 @@ user_del(){
     done
 
     if $guitool --question --text="$translated_message" ; then
-        $USERDEL -r "$username" 2>"${temp_error}" || exit_error
+        $USERDEL -r "$username" 2>"${temp_error}" || exit 1
     else
-        $USERDEL "$username" 2>"${temp_error}" || exit_error
+        $USERDEL "$username" 2>"${temp_error}" || exit 1
     fi
 
     sudoers_del "$username"
