improved debug for non-terminal mode

diff --git a/usr/lib/elive-tools/functions b/usr/lib/elive-tools/functions
--- a/usr/lib/elive-tools/functions
+++ b/usr/lib/elive-tools/functions
@@ -519,7 +519,7 @@ EOF
         fi
 
         if ! ((is_password_ok)) && [[ -n "$DISPLAY" ]] ; then
-            zenity --error
+            $guitool --error
         fi
     fi
     rm -f "${temp}"
@@ -587,7 +587,7 @@ el_aptget_update(){
                     done
 
                     if ! ((is_password_ok)) && [[ -n "$DISPLAY" ]] ; then
-                        zenity --error
+                        $guitool --error
                     fi
 
                 else
@@ -819,7 +819,7 @@ el_sudo(){
             done
 
             if ! ((is_password_ok)) && [[ -n "$DISPLAY" ]] ; then
-                zenity --error
+                $guitool --error
             fi
         else
             su -c "$@" root
@@ -1214,10 +1214,16 @@ el_warning(){
     # warning {{{
 
     if [[ "${EL_DEBUG}" -ge 1 ]] ; then
-        if [[ "${EL_DEBUG}" -ge 3 ]] ; then
-            echo -e "${el_c_y}Warning: ${el_c_c}[${el_c_b2}${FUNCNAME[1]}${el_c_c}:${el_c_b2}${BASH_LINENO}${el_c_c}] ${el_c_c}$@${el_c_n}" 1>&2
+        if ((is_terminal)) ; then
+            if [[ "${EL_DEBUG}" -ge 3 ]] ; then
+                echo -e "${el_c_y}Warning: ${el_c_c}[${el_c_b2}${FUNCNAME[1]}${el_c_c}:${el_c_b2}${BASH_LINENO}${el_c_c}] ${el_c_c}$@${el_c_n}" 1>&2
+            else
+                echo -e "${el_c_y}Warning: ${el_c_c}$@${el_c_n}" 1>&2
+            fi
         else
-            echo -e "${el_c_y}Warning: ${el_c_c}$@${el_c_n}" 1>&2
+            if [[ "$DISPLAY" = ":0.0" ]] && el_check_version_development ; then
+                $guitool --warning "$@"
+            fi
         fi
     fi
 
@@ -1238,10 +1244,16 @@ el_error(){
     # error {{{
 
     if [[ "${EL_DEBUG}" -ge 0 ]] ; then
-        if [[ "${EL_DEBUG}" -ge 3 ]] ; then
-            echo -e "${el_c_r}Error: ${el_c_c}[${el_c_b2}${FUNCNAME[1]}${el_c_c}:${el_c_b2}${BASH_LINENO}${el_c_c}] ${el_c_c}$@${el_c_n}" 1>&2
+        if ((is_terminal)) ; then
+            if [[ "${EL_DEBUG}" -ge 3 ]] ; then
+                echo -e "${el_c_r}Error: ${el_c_c}[${el_c_b2}${FUNCNAME[1]}${el_c_c}:${el_c_b2}${BASH_LINENO}${el_c_c}] ${el_c_c}$@${el_c_n}" 1>&2
+            else
+                echo -e "${el_c_r}Error: ${el_c_c}$@${el_c_n}" 1>&2
+            fi
         else
-            echo -e "${el_c_r}Error: ${el_c_c}$@${el_c_n}" 1>&2
+            if [[ "$DISPLAY" = ":0.0" ]] && el_check_version_development ; then
+                $guitool --error "$@"
+            fi
         fi
     fi
 
@@ -1301,7 +1313,7 @@ el_group_add(){
         done
 
         if ! ((is_password_ok)) && [[ -n "$DISPLAY" ]] ; then
-            zenity --error --text="$( eval_gettext "Wrong password" )"
+            $guitool --error --text="$( eval_gettext "Wrong password" )"
         fi
 
 
@@ -1320,7 +1332,7 @@ el_group_add(){
             done
 
             if ! ((is_password_ok)) && [[ -n "$DISPLAY" ]] ; then
-                zenity --error
+                $guitool --error
             fi
         fi
 
