implemented debug, info, warning, error functions

diff --git a/usr/lib/elive-tools/functions b/usr/lib/elive-tools/functions
--- a/usr/lib/elive-tools/functions
+++ b/usr/lib/elive-tools/functions
@@ -328,10 +328,11 @@ el_check_sudo_automated(){
 }
 #===  FUNCTION  ================================================================
 #          NAME:  el_explain
-#   DESCRIPTION:  function to show the process of this tool
+#   DESCRIPTION:  function to show the progress of the application
 #    PARAMETERS:
-# verbose_level:       $1 = 1-5* from $EL_DEBUG levels
-#        spaced:       $2 = infinite,
+# verbose_level:    $1 = any number, from $EL_DEBUG levels
+#                        levels: 0 = always, 1 = info, 2 = debug
+#        detail:    $2 = infinite, number of spaces for identify detailed info
 #       message:       $3 = can include: __hilight words__, XXsuper hilightXX
 #===============================================================================
 el_explain(){
@@ -416,6 +417,76 @@ el_explain(){
 
    # }}}
 }
+#===  FUNCTION  ================================================================
+#          NAME:  el_debug
+#   DESCRIPTION:  show debug messages | EL_DEBUG -ge 1
+#    PARAMETERS:  optional (message)
+#===============================================================================
+el_debug(){
+    # debug {{{
+    if [[ "${EL_DEBUG}" -ge 2 ]] ; then
+        # level 2 is debug
+        echo -e "${el_c_gr}D: ${el_c_b2}${FUNCNAME[1]}${el_c_c}:${el_c_b2}${BASH_LINENO} ${el_c_c}$@${el_c_n}" 1>&2
+
+    fi
+
+    # }}}
+}
+
+#===  FUNCTION  ================================================================
+#          NAME:  el_warning
+#   DESCRIPTION:  show warning messages | EL_DEBUG -ge 1
+#    PARAMETERS:  optional (message)
+#===============================================================================
+el_warning(){
+    # warning {{{
+    if [[ "${EL_DEBUG}" -ge 1 ]] ; then
+        echo -e "${el_c_y}Warning: ${el_c_c}[${el_c_b2}${FUNCNAME[1]}${el_c_c}:${el_c_b2}${BASH_LINENO}${el_c_c}] ${el_c_c}$@${el_c_n}" 1>&2
+
+    fi
+
+    # }}}
+}
+
+#===  FUNCTION  ================================================================
+#          NAME:  el_error
+#   DESCRIPTION:  show error messages | EL_DEBUG -ge 0
+#    PARAMETERS:  optional (message)
+#===============================================================================
+el_error(){
+    # error {{{
+    if [[ "${EL_DEBUG}" -ge 0 ]] ; then
+        echo -e "${el_c_r}Error: ${el_c_c}[${el_c_b2}${FUNCNAME[1]}${el_c_c}:${el_c_b2}${BASH_LINENO}${el_c_c}] ${el_c_c}$@${el_c_n}" 1>&2
+
+    fi
+
+    # }}}
+}
+
+
+
+
+
+
+
+
+# FIXME: implement:
+# FIXME: implement:
+# FIXME: implement:
+#
+# - check same proceses
+# - el_fixme_required -> report to the user that the feature is not implemented by some future userfriendly way
+# - arrays ?
+# - run web
+# - confirm (shell)
+# - trap signals (exit statuses, etc)
+# - report, something for inform the user about something important, which interfaces and cases ?
+# -
+# -
+# -
+# -
+# -
+# -
 
 
 # vim: set foldmethod=marker :
