added function to get machine id

diff --git a/usr/lib/elive-tools/functions b/usr/lib/elive-tools/functions
--- a/usr/lib/elive-tools/functions
+++ b/usr/lib/elive-tools/functions
@@ -2824,6 +2824,92 @@ el_ram_usage_show(){
 
 }
 
+#===  FUNCTION  ================================================================
+#          NAME:  el_get_machine_id
+#   DESCRIPTION:  get a unique machine identifier (root)
+#    PARAMETERS:  -
+#       RETURNS:  value id
+#===============================================================================
+el_get_machine_id(){
+    # pre {{{
+    local machine_id
+    #el_debug
+    #el_security_function_loop || return
+
+    if ! [[ "$UID" = 0 ]] ; then
+        el_error "$FUNCNAME must be run with privileges"
+        return 1
+    fi
+
+    # }}}
+
+    # get board serial number
+    machine_id="$( cat /sys/class/dmi/id/board_serial )"
+    read -r machine_id <<< "$machine_id"
+    if [[ "$machine_id" = INVALID ]] || [[ "$machine_id" = Not* ]] ; then
+        unset machine_id
+    else
+        machine_id="boardserial${machine_id}"
+    fi
+
+    # get system serial number
+    if [[ -z "$machine_id" ]] || [[ "$machine_id" = 0 ]] ; then
+        machine_id="$( dmidecode -s system-serial-number )"
+    fi
+    if [[ "$machine_id" = INVALID ]] || [[ "$machine_id" = Not* ]] ; then
+        unset machine_id
+    else
+        machine_id="systemserialnumber${machine_id}"
+    fi
+
+    # get system uuid
+    if [[ -z "$machine_id" ]] || [[ "$machine_id" = 0 ]] ; then
+        machine_id="$( dmidecode -s system-uuid )"
+    fi
+    if [[ "$machine_id" = INVALID ]] || [[ "$machine_id" = Not* ]] ; then
+        unset machine_id
+    else
+        machine_id="systemuuid${machine_id}"
+    fi
+
+    # get product name
+    if [[ -z "$machine_id" ]] || [[ "$machine_id" = 0 ]] ; then
+        machine_id="$( dmidecode -s system-product-name )"
+    fi
+    if [[ "$machine_id" = INVALID ]] || [[ "$machine_id" = Not* ]] ; then
+        unset machine_id
+    fi
+
+    # pack a combination of identifiers to make sure we have a machine id
+    if [[ -z "$machine_id" ]] || [[ "$machine_id" = 0 ]] ; then
+        machine_id="$( dmidecode -s bios-vendor )$machine_id"
+        machine_id="$( dmidecode -s bios-version )$machine_id"
+        machine_id="$( dmidecode -s system-manufacturer )$machine_id"
+        machine_id="$( dmidecode -s system-product-name )$machine_id"
+        machine_id="$( echo "$( echo "$machine_id" ; cat /proc/cpuinfo 2>/dev/null | grep -E "(model name|model|cpu family)" 2>/dev/null | sort -u 2>/dev/null | psort -- -p "^model.*:" | head -1 )" | md5sum 2>/dev/null | awk '{print $1}' 2>/dev/null )"
+        read -r machine_id <<< "$machine_id"
+        machine_id="packed${machine_id}"
+    fi
+
+    # cleanups and backup
+    if [[ -n "$machine_id" ]] ; then
+        machine_id="#machine-id:${machine_id}"
+    else
+        # re-use a backup if we cannot fetch machine-id in shutdown step
+        if [[ -e "/tmp/.machine-id" ]] ; then
+            machine_id="$( cat /tmp/.machine-id 2>/dev/null )"
+            read -r machine_id <<< "$machine_id"
+        fi
+    fi
+
+    # show results
+    if [[ -n "$machine_id" ]] ; then
+        echo "$machine_id"
+    else
+        el_error "no machine id found"
+    fi
+}
+
 
 
 ###################################################################
