independency from functions file, because this tool should be used everywhere in the entire world!

diff --git a/usr/bin/bkp b/usr/bin/bkp
--- a/usr/bin/bkp
+++ b/usr/bin/bkp
@@ -1,9 +1,313 @@
 #!/bin/bash
-source /usr/lib/elive-tools/functions
-el_make_environment
-#TEXTDOMAIN=""
-#export TEXTDOMAIN
 set -e
+el_c_n="\033[0;39m" # Normal color  (orig: normal)
+el_c_r="\033[1;31m" # Red color  (orig: red)
+el_c_r2="\033[0;31m" # Red2 color  (orig: red)
+el_c_g="\033[1;32m" # Green color  (orig: green)
+el_c_g2="\033[0;32m" # Green2 color  (orig. green2)
+el_c_y="\033[1;33m" # Yellow color  (orig. yellow)
+el_c_y2="\033[0;33m" # Yellow2 color  (orig. yellow)
+el_c_m="\033[1;35m" # Magenta color
+el_c_m2="\033[0;35m" # Magenta2 color
+el_c_c="\033[1;36m" # Cyan color
+el_c_c2="\033[0;36m" # Cyan2 color
+el_c_b="\033[1;34m" # Blue color
+el_c_b2="\033[0;34m" # Blue2 color
+el_c_gr="\033[1;30m" # Gray color
+el_c_gr2="\033[0;30m" # Gray2 color
+
+el_c_blink="\033[5m" # Blink 'color' effect  (orig. blink)
+el_c_underline="\033[4m" # Underline 'color' effect  (orig. underline)
+el_c_italic="\033[3m" # Italic 'color' effect
+el_c_bold="\033[1m" # Bold 'color' effect
+
+: ${EL_DEBUG:="0"} # debug default level
+
+
+#===  FUNCTION  ================================================================
+#          NAME:  el_confirm
+#   DESCRIPTION:  ask (console) for confirmation
+#    PARAMETERS:  question
+#       RETURNS:  true | false
+#===============================================================================
+el_confirm(){
+    # pre {{{
+    local reply question flag_glob
+
+    if shopt extglob | grep -q "extglob.*off" ; then
+        flag_glob=1
+    fi
+
+    shopt -s extglob
+    question="$1"
+
+    el_check_variables "question"
+
+
+    # }}}
+    # return answer {{{
+    echo -en "$question [y/n]: "
+    read reply
+
+    case $reply in
+        y|Y|Yes|YES|s|S)
+            return  0
+            ;;
+        n|N|no|NO|nope)
+            return  1
+            ;;
+        *)
+            # repeat question until confirmation
+            if el_confirm "$@" ; then
+                return 0
+            else
+                return 1
+            fi
+            ;;
+    esac
+
+    if ((flag_glob)) ; then
+        shopt -u extglob
+    fi
+
+    # }}}
+}
+#===  FUNCTION  ================================================================
+#          NAME:  el_error
+#   DESCRIPTION:  show error messages | EL_DEBUG -ge 0
+#    PARAMETERS:  optional (message)
+#===============================================================================
+el_error(){
+    # error {{{
+
+    if [[ "${EL_DEBUG}" -ge 0 ]] ; then
+        echo -e "${el_c_r}Error: ${el_c_c}[${el_c_b2}${FUNCNAME[1]}${el_c_c}:${el_c_b2}${BASH_LINENO}${el_c_c}] ${el_c_c}$@${el_c_n}" 1>&2
+
+    fi
+
+    # }}}
+}
+#===  FUNCTION  ================================================================
+#          NAME:  el_warning
+#   DESCRIPTION:  show warning messages | EL_DEBUG -ge 1
+#    PARAMETERS:  optional (message)
+#===============================================================================
+el_warning(){
+    # warning {{{
+
+    if [[ "${EL_DEBUG}" -ge 1 ]] ; then
+        echo -e "${el_c_y}Warning: ${el_c_c}[${el_c_b2}${FUNCNAME[1]}${el_c_c}:${el_c_b2}${BASH_LINENO}${el_c_c}] ${el_c_c}$@${el_c_n}" 1>&2
+    fi
+
+    # }}}
+}
+#===  FUNCTION  ================================================================
+#          NAME:  el_explain
+#   DESCRIPTION:  function to show the progress of the application
+#    PARAMETERS:
+# verbose_level:    $1 = any number, from $EL_DEBUG levels
+#                        levels: 0 = always, 1 = info, 2 = debug
+#       message:    $2 = can include: __hilight words__, XXsuper hilightXX
+#===============================================================================
+el_explain(){
+    # pre {{{
+    local funclevel spaced verbose_level message trace_message trace_col
+
+    verbose_level="$1"
+    shift
+    message="$@"
+
+    spaced="$verbose_level"
+    funclevel="$(( ${#FUNCNAME[*]} - 2 ))"
+
+    el_check_variables "spaced,verbose_level,message"
+    # }}}
+    # tabulate output {{{
+    while [[ $spaced -gt 0 ]] ; do
+        message="  $message"
+        spaced="$(( $spaced - 1 ))"
+    done
+
+    # }}}
+    # hilight words {{{
+    message="${message/__/${el_c_b2}}"
+    message="${message/__/${el_c_gr}}"
+    message="${message/__/${el_c_b2}}"
+    message="${message/__/${el_c_gr}}"
+    message="${message/__/${el_c_b2}}"
+    message="${message/__/${el_c_gr}}"
+    message="${message/XX/${el_c_r}}"
+    message="${message/XX/${el_c_gr}}"
+    message="${message/XX/${el_c_r}}"
+    message="${message/XX/${el_c_gr}}"
+    # }}}
+    # show {{{
+    # this is a good example of levels of colors visualization for the user's eye
+
+    # show only if we are on this verbose level
+    if [[ "${EL_DEBUG}" -ge "$verbose_level" ]] ; then
+        case $funclevel in
+            1)
+                echo -en "   ${el_c_gr}[${el_c_b2}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            2)
+                echo -en "   ${el_c_gr}[${el_c_b}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            3)
+                echo -en "   ${el_c_gr}[${el_c_c2}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            4)
+                echo -en "   ${el_c_gr}[${el_c_c}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            5)
+                echo -en "   ${el_c_gr}[${el_c_g2}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            6)
+                echo -en "   ${el_c_gr}[${el_c_g}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            7)
+                echo -en "   ${el_c_gr}[${el_c_y2}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            8)
+                echo -en "   ${el_c_gr}[${el_c_y}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            9)
+                echo -en "   ${el_c_gr}[${el_c_r2}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            10)
+                echo -en "   ${el_c_gr}[${el_c_r}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            11)
+                echo -en "   ${el_c_gr}[${el_c_m2}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+            *)
+                echo -en "   ${el_c_gr}[${el_c_m}${funclevel}${el_c_gr}] " 1>&2
+                ;;
+        esac
+
+        # continuation of the message
+        echo -e "${message}${el_c_n}" 1>&2
+
+    fi
+
+    # }}}
+}
+#-------------------------------------------------------------------------------
+#   Check if variable exists
+#-------------------------------------------------------------------------------
+el_check_variables(){
+    # check if we have set these variables, if not, notify and exit {{{
+    # example $0 foo,bar,we
+    local found_no var
+
+    while read -ru 3 var
+    do
+        if [[ ! -n "${!var}" ]] ; then
+            #el_notify_user "E: Variable not exists" "E: the variable '$var' is not set"
+            el_error "Variable '$var' is not set"
+            found_no="yes"
+        fi
+    done 3<<< "$( echo "$@" | tr ',' '\n' )"
+
+    if [[ "$found_no" = "yes" ]] ; then
+
+        return 1
+    else
+
+        return 0
+    fi
+
+    # }}}
+}
+#-------------------------------------------------------------------------------
+#   Dependencies Check
+#	example:  el_dependencies_check gmplayer,find,sed,etc
+#-------------------------------------------------------------------------------
+el_dependencies_check(){
+    # check if we have these command dependencies, if not, notify and exit {{{
+    local check found found_no dir
+
+    while read -ru 3 check
+    do
+        unset found
+
+        for dir in $(echo ${PATH}:/usr/local/sbin:/usr/sbin:/sbin | tr ':' ' ')
+        do
+            if test -x ${dir}/$check
+            then
+                found=yes
+                break
+            fi
+        done
+
+        if [[ "$found" != "yes" ]] ; then
+            el_error "Command '$check' for $(basename $0) not found"
+            found_no="yes"
+        fi
+
+    done 3<<< "$( echo "$@" | tr ',' '\n' )"
+
+    if [[ "$found_no" = "yes" ]] ; then
+
+        return 1
+    else
+
+        return 0
+    fi
+    # }}}
+}
+#-------------------------------------------------------------------------------
+#   check if we have automatic sudo
+#-------------------------------------------------------------------------------
+el_check_sudo_automated(){
+    # {{{
+
+    if ! sudo -H -n echo 2>/dev/null 1>/dev/null ; then
+        #el_notify_user "Automated sudo is required" "Your sudo requires a password, we need it to be configured for not request it"
+        el_error "Automated sudo is required: Your sudo requires a password, we need it to be configured for not request it"
+
+        return 1
+    else
+
+        return 0
+    fi
+
+    # }}}
+}
+#-------------------------------------------------------------------------------
+#   Install required packages
+#-------------------------------------------------------------------------------
+el_dependencies_install(){
+    # install required dependencies {{{
+    local depends temp
+    depends="$( echo "$@" | tr ',' ' ' )"
+    el_set_display_variables
+
+    # TODO:  even better: use a gui tool for install deps
+    el_dependencies_check urxvt
+
+    temp="/tmp/.$(basename $0)-${USER}-$$"
+    cat > "${temp}" << EOF
+#!/bin/bash
+
+urxvt -e bash -c "echo -e 'Installing Dependencies...' ; sleep 1 ; apt-get update ; apt-get -f install ; apt-get install $depends ; echo ; echo ; echo ; echo ; echo 'Finished, you can close the terminal...' ; sleep 20 "
+
+EOF
+
+    chmod +x "${temp}"
+    gksu "${temp}"
+    rm -f "${temp}"
+
+    # }}}
+}
+
+
+
+
+
+
+# I assume that this is not needed anymore at all
+#el_make_environment
 
 do_work(){
     # this feature does a temporal copy of the directory for work from it,
