fixing identation

diff --git a/usr/bin/el_package_update_last_version b/usr/bin/el_package_update_last_version
--- a/usr/bin/el_package_update_last_version
+++ b/usr/bin/el_package_update_last_version
@@ -13,12 +13,12 @@ main(){
 
     # Usage
     if [[ -z "${1}" ]] ; then
-	echo -e "Usage: $(basename $BASH_SOURCE) packagename [--force]"
-	exit 1
+        echo -e "Usage: $(basename $BASH_SOURCE) packagename [--force]"
+        exit 1
     fi
 
     if [[ "$2" = "--force" ]] ; then
-	is_mode_force=1
+        is_mode_force=1
     fi
 
     packagename="${1}"
@@ -26,18 +26,18 @@ main(){
 
     # check internet
     if ! el_verify_internet ; then
-	el_explain 1 "No internet found, ignoring checking of newer packages available"
-	exit 1
+        el_explain 1 "No internet found, ignoring checking of newer packages available"
+        exit 1
     fi
 
     # check repo url
     if ! el_check_variables "url_repository" ; then
-	el_error "no url found for ${packagename} package, ignoring check in $(basename $0)"
-	exit
+        el_error "no url found for ${packagename} package, ignoring check in $(basename $0)"
+        exit
     fi
 
     if ! el_dependencies_check "apt-get,apt-cache,zenity,dpkg" ; then
-	exit 1
+        exit 1
     fi
 
 
@@ -49,20 +49,20 @@ main(){
     # first pass, check if we can have a possible candidate (fuzzy mode) {{{
     while read -ru 3 line
     do
-	url_package_dir="${url_repository%/}/${line%/*}/"
+        url_package_dir="${url_repository%/}/${line%/*}/"
 
-	# compare all teh versions found with a simple curl with the installed version
-	while read -ru 3 version
-	do
-	    # cleanup var and url-decode it
-	    read -r version <<< "$version"
-	    #version="$( hURL -us --nocolor "$version" )"
-	    version="$( printf "$( echo "$version" | sed -e 's|%|\\x|g' )" )"
+        # compare all teh versions found with a simple curl with the installed version
+        while read -ru 3 version
+        do
+            # cleanup var and url-decode it
+            read -r version <<< "$version"
+            #version="$( hURL -us --nocolor "$version" )"
+            version="$( printf "$( echo "$version" | sed -e 's|%|\\x|g' )" )"
 
-	    if dpkg --compare-versions "${version}" gt "${package_version_installed}" 2>/dev/null ; then
-		package_version_newer_found_maybe=1
-	    fi
-	done 3<<< "$( curl -s "${url_package_dir}" | grep href | sed -e 's|^.*href="||g' -e 's|".*$||g' | grep '\.deb$' | cut -d'_' -f2 | sort -u )"
+            if dpkg --compare-versions "${version}" gt "${package_version_installed}" 2>/dev/null ; then
+                package_version_newer_found_maybe=1
+            fi
+        done 3<<< "$( curl -s "${url_package_dir}" | grep href | sed -e 's|^.*href="||g' -e 's|".*$||g' | grep '\.deb$' | cut -d'_' -f2 | sort -u )"
 
     done 3<<< "$( apt-cache show "${packagename}" 2>/dev/null | grep "Filename:" | sed -e 's|^Filename: ||g' | sort -u )"
 
@@ -72,8 +72,8 @@ main(){
     # checking results and deciding {{{
     # nothing found in a first shot?
     if ! ((package_version_newer_found_maybe)) ; then
-	# return false if we have not updated or found anything
-	exit 1
+        # return false if we have not updated or found anything
+        exit 1
     fi
 
 
@@ -84,42 +84,42 @@ main(){
     # install new package if found
     if el_package_newer_check "${packagename}" ; then
 
-	local message_upgrade_please message_upgrade_force
-	message_upgrade_please="$( printf "$( eval_gettext "Newer version found for %s, we suggest to update it, continue?" )" "$packagename" )"
+        local message_upgrade_please message_upgrade_force
+        message_upgrade_please="$( printf "$( eval_gettext "Newer version found for %s, we suggest to update it, continue?" )" "$packagename" )"
 
-	message_upgrade_force="$( printf "$( eval_gettext "The package %s needs to be updated before to continue." )" "$packagename" )"
+        message_upgrade_force="$( printf "$( eval_gettext "The package %s needs to be updated before to continue." )" "$packagename" )"
 
-	if [[ -n "$DISPLAY" ]] ; then
-	    if ((is_mode_force)) ; then
-		zenity --info --text="$message_upgrade_force"
-		el_dependencies_install "$packagename"
-		exit 0
-	    else
-		if zenity --question --text="$message_upgrade_please" ; then
-		    el_dependencies_install "$packagename"
-		    exit 0
-		else
-		    exit 1
-		fi
-	    fi
+        if [[ -n "$DISPLAY" ]] ; then
+            if ((is_mode_force)) ; then
+                zenity --info --text="$message_upgrade_force"
+                el_dependencies_install "$packagename"
+                exit 0
+            else
+                if zenity --question --text="$message_upgrade_please" ; then
+                    el_dependencies_install "$packagename"
+                    exit 0
+                else
+                    exit 1
+                fi
+            fi
 
-	else
-	    if ((is_mode_force)) ; then
-		echo -e "The package $packagename needs to be updated.\nPlease insert root/admin password:"
-		su -c "apt-get install $packagename" root
-		exit 0
-	    else
-		if el_confirm "$message_upgrade_please" ; then
-		    echo -e "Please insert root/admin password:"
-		    su -c "apt-get install $packagename" root
-		    exit 0
-		else
-		    exit 1
-		fi
-	    fi
-	fi
+        else
+            if ((is_mode_force)) ; then
+                echo -e "The package $packagename needs to be updated.\nPlease insert root/admin password:"
+                su -c "apt-get install $packagename" root
+                exit 0
+            else
+                if el_confirm "$message_upgrade_please" ; then
+                    echo -e "Please insert root/admin password:"
+                    su -c "apt-get install $packagename" root
+                    exit 0
+                else
+                    exit 1
+                fi
+            fi
+        fi
     else
-	exit 1
+        exit 1
     fi
 
 
@@ -130,4 +130,4 @@ main(){
 #
 main "$@"
 
-# vim: set foldmethod=marker :
+# vim: set foldmethod=marker expandtab :
