some rewrite for the updater of packages

diff --git a/usr/bin/el_package_update_last_version b/usr/bin/el_package_update_last_version
--- a/usr/bin/el_package_update_last_version
+++ b/usr/bin/el_package_update_last_version
@@ -27,9 +27,20 @@ main(){
             -f|--force)
                 is_mode_force=1
                 ;;
+            -a|--automated)
+                is_automated=1
+                is_quiet=1
+                ;;
             -h|--help)
                 usage
                 exit
+                ;;
+            -q|--quiet)
+                is_quiet=1
+                ;;
+            -c|--check)
+                # check only and exit, return value is used
+                is_check_only=1
                 ;;
             *)
                 if [[ -n "$packagename" ]] ; then
@@ -72,14 +83,6 @@ main(){
     fi
 
 
-    # force update
-    if ((is_mode_force)) ; then
-        el_aptget_update force
-    else
-        el_aptget_update
-    fi
-
-
     # }}}
 
     package_version_installed="$( LC_ALL=C  apt-cache policy "${packagename}" | grep "Installed:" | sed -e 's|^.*Installed: ||g' | head -1 )"
@@ -114,8 +117,16 @@ main(){
         exit 1
     fi
 
+    # return true always, if we arrived here
+    if ((is_check_only)) ; then
+        exit 0
+    fi
+
 
     # - checking results and deciding }}}
+
+    # make sure that we update caches or we will be unable to install it
+    el_aptget_update force
 
     # install new package if found
     if el_package_newer_check "${packagename}" ; then
@@ -125,36 +136,72 @@ main(){
 
         message_upgrade_force="$( printf "$( eval_gettext "The package %s needs to be updated." )" "${packagename%:*}" )"
 
-        if [[ -n "$DISPLAY" ]] ; then
-            if ((is_mode_force)) ; then
-                zenity --info --text="$message_upgrade_force" || true
-                if ! el_dependencies_install "$packagename" ; then
-                    exit 1
+        # install
+        if ((is_automated)) ; then
+            if [[ "$UID" = 0 ]] ; then
+                if ! timeout 900 DEBIAN_FRONTEND=noninteractive apt-get -f install ; then
+                    el_error "problem with apt-get -f install"
                 fi
-                exit 0
+                if ! timeout 900 DEBIAN_FRONTEND=noninteractive apt-get install -y $packagename ; then
+                    el_error "problem with apt-get install -y $packagename"
+                fi
             else
-                if zenity --question --text="$message_upgrade_please" ; then
+                el_error "$(basename $0) called in automated mode and we are non-root, how we should proceed? ignoring..."
+            fi
+        else
+            if [[ -n "$DISPLAY" ]] ; then
+                if ((is_mode_force)) ; then
+                    if ! ((is_quiet)) ; then
+                        zenity --info --text="$message_upgrade_force" || true
+                    fi
                     if ! el_dependencies_install "$packagename" ; then
                         exit 1
                     fi
                     exit 0
                 else
-                    exit 1
+                    if ((is_quiet)) ; then
+                        if ! el_dependencies_install "$packagename" ; then
+                            exit 1
+                        fi
+                        exit 0
+                    else
+                        if zenity --question --text="$message_upgrade_please" ; then
+                            if ! el_dependencies_install "$packagename" ; then
+                                exit 1
+                            fi
+                            exit 0
+                        else
+                            exit 1
+                        fi
+                    fi
                 fi
-            fi
 
-        else
-            if ((is_mode_force)) ; then
-                echo -e "The package $packagename needs to be updated.\nPlease insert root/admin password:"
-                su -c "DEBIAN_FRONTEND=noninteractive apt-get install $packagename" root
-                exit 0
             else
-                if el_confirm "$message_upgrade_please" ; then
-                    echo -e "Please insert root/admin password:"
-                    su -c "DEBIAN_FRONTEND=noninteractive apt-get install $packagename" root
-                    exit 0
+                if ((is_terminal)) ; then
+                    if ((is_mode_force)) ; then
+                        echo -e "The package $packagename needs to be updated.\nPlease insert root/admin password:"
+                        su -c "DEBIAN_FRONTEND=noninteractive apt-get install $packagename" root
+                        exit 0
+                    else
+                        if el_confirm "$message_upgrade_please" ; then
+                            echo -e "Please insert root/admin password:"
+                            su -c "DEBIAN_FRONTEND=noninteractive apt-get install $packagename" root
+                            exit 0
+                        else
+                            exit 1
+                        fi
+                    fi
                 else
-                    exit 1
+                    if [[ "$UID" = 0 ]] ; then
+                        if ! timeout 900 DEBIAN_FRONTEND=noninteractive apt-get -f install ; then
+                            el_error "problem with apt-get -f install"
+                        fi
+                        if ! timeout 900 DEBIAN_FRONTEND=noninteractive apt-get install -y $packagename ; then
+                            el_error "problem with apt-get install -y $packagename"
+                        fi
+                    else
+                        el_error "$(basename $0) called outside graphical system and outside terminal and non-root mode, how we should proceed? ignoring..."
+                    fi
                 fi
             fi
         fi
