speak text support in buster

diff --git a/usr/bin/el_speak_text b/usr/bin/el_speak_text
--- a/usr/bin/el_speak_text
+++ b/usr/bin/el_speak_text
@@ -37,7 +37,7 @@ main(){
     # }}}
 
     # this trick is required because an ugly tmp.lab file is created in the home
-    mkdir -p /tmp/.$(basename $0)-$USER-$$
+    mkdir -p /tmp/.$(basename $0)-$USER-$$  "$HOME/.cache/el_speak"
     cd /tmp/.$(basename $0)-$USER-$$
 
     # wait for someone that finishes to speak before to start speaking
@@ -53,8 +53,22 @@ main(){
     # futuristic + less echo + more chorus in background
     #echo "${text}" | iconv -f utf8 -t ISO-8859-15 | text2wave -f 48000 -otype riff -scale 0.8 | play -q -t wav - tempo 1.0 pad 0 3 flanger reverb 40 50 100 100 75 3 norm 2  2>/dev/null
 
-    echo "${text}" | iconv -f utf8 -t ISO-8859-15 | text2wave -f 48000 -otype riff -scale 0.8 | play -q -t wav - tempo 1.0 pad 0 2 flanger reverb 40 50 100 100 75 3 norm 4  2>/dev/null
-    echo "$text" >> /tmp/.$(basename $0)-${USER}-log.txt
+    #echo "${text}" | iconv -f utf8 -t ISO-8859-15 | text2wave -f 48000 -otype riff -scale 0.8 | play -q -t wav - tempo 1.0 pad 0 2 flanger reverb 40 50 100 100 75 3 norm 4  2>/dev/null
+
+    # save a copy of the voice
+    if ! [[ -s "$HOME/.cache/el_speak/${text}.wav" ]] ; then
+        echo "${text}" | iconv -f utf8 -t ISO-8859-15 | text2wave -f 48000 -otype riff -scale 0.8 > "$HOME/.cache/el_speak/${text}.wav"
+    fi
+    # if we have the voice, play it, with effects
+    if [[ -s "$HOME/.cache/el_speak/${text}.wav" ]] ; then
+        play -q -t wav "$HOME/.cache/el_speak/${text}.wav" tempo 1.0 pad 0 2 flanger reverb 40 50 100 100 75 3 norm 4  2>/dev/null
+    fi
+
+    # cleanup space
+    cd "$HOME/.cache/el_speak"
+    ls -1tr | head -n "-40" | xargs rm -f
+
+    #echo "$text" >> /tmp/.$(basename $0)-${USER}-log.txt
 
     cd - 1>/dev/null
     rm -rf /tmp/.$(basename $0)-$USER-$$
@@ -67,5 +81,6 @@ el_dependencies_check "text2wave,play,sox,iconv"
 
 { main "$@" & disown ; } 2>/dev/null
 #main "$@"
+
 # vim: set foldmethod=marker :
 
