auto: untarzanice | PLEASE review this commit @Thanatermesis

diff --git a/usr/bin/elive-run-file-helper b/usr/bin/elive-run-file-helper
--- a/usr/bin/elive-run-file-helper
+++ b/usr/bin/elive-run-file-helper
@@ -20,7 +20,7 @@ not_supported(){
 
 run_dmg(){
     local message_dmg
-    message_dmg="$( printf "$( eval_gettext "DMG files belong to macOS systems. You cannot create or modify them in Linux, but you can open them so you can extract its content. Do you want to open it now?" )" "" )"
+    message_dmg="$( printf "$( eval_gettext "DMG files belong to MacOS systems. You cannot create or modify them in Linux, but you can open them so you can view or extract their content. Do you want to open it now?" )" "" )"
 
     if $guitool --question --text="$message_dmg" ; then
         filename="$( basename "$file" )"
@@ -48,7 +48,7 @@ run_e16(){
     case "$mode" in
         theme)
             if [[ -z "$EROOT" ]] ; then
-                $guitool --error --text="$( eval_gettext "This is an Enlightenment 16 theme, but you are not running this window manager, start your graphical system in order to be able to use this file." )"
+                $guitool --error --text="$( eval_gettext "This is an Enlightenment 16 theme, login into this window manager in order to be able to use this file." )"
                 return
             fi
             mkdir -p "$HOME/.e16/themes"
@@ -97,7 +97,7 @@ run_edje(){
             $precmd cp -f "$file" "$HOME/.e/e17/themes/"
             # update: seems like it doesn't works?
             #enlightenment_remote -theme-set
-            $guitool --info --text="$( eval_gettext "You can now activate the new theme from the preferences menu. Note that they may not always be fully compatible, we suggest to use the Elive theme for compatibility, stability and features." )"
+            $guitool --info --text="$( eval_gettext "You can now activate the new theme from the preferences menu. Note that they may not always be fully compatible, we suggest using the Elive theme for compatibility, stability, and having the most features." )"
 
         fi
 
@@ -130,7 +130,7 @@ run_script(){
     fi
 
     # warn user
-    if ! $guitool --question --text="$( eval_gettext "You are going to execute a file, since they can run arbitrary code on your machine, it is important to always verify that it came from a well-known, trusted author or source. Continue?" )" ; then
+    if ! $guitool --question --text="$( eval_gettext "You are going to execute a file, and since they can run arbitrary code on your machine, it is very important to know it comes from a well-known author or trusted source. Continue?" )" ; then
         return 0
     fi
 
@@ -142,7 +142,7 @@ run_script(){
     #fi
 
     if ! [[ "$UID" = 0 ]] ; then
-        if $guitool --question --cancel-label="$( eval_gettext "No" )" --ok-label="$( eval_gettext "Yes" )" --text="$( eval_gettext "Do you need administrator privileges to run this file? This is commonly needed if you are trying to install software or a driver to your system. We suggest to first try to run the file without the administrator privileges." )" ; then
+        if $guitool --question --cancel-label="$( eval_gettext "No" )" --ok-label="$( eval_gettext "Yes" )" --text="$( eval_gettext "Do you need administrator privileges to run this file? This is commonly needed if you are trying to install software or a driver to your system. We suggest first trying to run the file without admin privileges." )" ; then
             is_root_wanted=1
         fi
     fi
@@ -175,7 +175,7 @@ run_script(){
     # AppImage files
     if echo "$file" | grep -qsi ".*\.AppImage$" ; then
 
-        if ! $guitool --question --cancel-label="$( eval_gettext "No" )" --ok-label="$( eval_gettext "Yes" )" --text="$( eval_gettext "Run this AppImage it in sandbox mode? Strongly suggested for security reasons unless you need to run it in your own system" )" ; then
+        if ! $guitool --question --cancel-label="$( eval_gettext "No" )" --ok-label="$( eval_gettext "Yes" )" --text="$( eval_gettext "Run this AppImage it in sandbox mode? Strongly suggested for security reasons unless you need to run it under your own system" )" ; then
             options_appimage="--no-sandbox ${options_appimage}"
         fi
 
@@ -349,10 +349,10 @@ main(){
                 run_e16 "theme" "$file"
                 ;;
             "application/x-iso9660-image")
-                $guitool --info --text="$( eval_gettext "This is an ISO image file, you can burn it to a DVD or a USB device; Elive includes a special tool for the latter. You can also mount it and open its contents by right-clicking the file which is also an Elive feature." )"
+                $guitool --info --text="$( eval_gettext "This is an ISO image file, you can burn it to a DVD or a USB device; Elive includes its own tool to record correctly USBs. You can also mount it and view its contents by right-clicking the file, which is also an Elive feature." )"
                 ;;
             "regular file, no read permission")
-                $guitool --error --text="$( eval_gettext "You have no read permission for this file. If you need to read it, open your file manager in Admin mode by right-clicking on the directory, then change the properties of the file you want to use." )"
+                $guitool --error --text="$( eval_gettext "You have no read permission for this file. If you need to read it, open your file manager in Admin mode by right-clicking on its directory, then you can change the read permissions of the file you want to use." )"
                 ;;
             *)
                 # already supported by default list (they just works using thunar), tested with starting by application/
