feature common smtp to configure the email tool

diff --git a/usr/bin/email-sender b/usr/bin/email-sender
--- a/usr/bin/email-sender
+++ b/usr/bin/email-sender
@@ -296,7 +296,9 @@ do_validate_sending(){
 
     # }}}
 
-    echo "This is a verification email send by your own computer, seems like it works so just delete or ignore me" | mutt -F "$conf_mutt" -s "testing elive email ($random)" "$email_account"
+    if ! echo "This is a verification email send by your own computer, seems like it works so just delete or ignore me" | mutt -F "$conf_mutt" -s "testing elive email ($random)" "$email_account" ; then
+        $guitool --error --text="$( eval_gettext "Seems like there was a problem sending a test email. Please verify your settings." )"
+    fi
     #sleep 2
 
 
@@ -319,34 +321,51 @@ do_validate_sending(){
                 return 1
             fi
             ;;
-    esac
 
-    for i in 1 2 3 4 5 6 7
-    do
-        result="$( curl -u "${email_account}:${email_password}" --silent "https://mail.google.com/mail/feed/atom" | sed -e 's|<entry>|\n\n<entry>|g' | grep "<entry>" | sed -e 's|^.*<title>||g' -e 's|</title>.*$||g' | head -3 )"
+        *@gmail*|Gmail)
+            for i in 1 2 3 4 5 6 7
+            do
+                result="$( curl -u "${email_account}:${email_password}" --silent "https://mail.google.com/mail/feed/atom" | sed -e 's|<entry>|\n\n<entry>|g' | grep "<entry>" | sed -e 's|^.*<title>||g' -e 's|</title>.*$||g' | head -3 )"
 
-        if echo "$result" | grep -qs "testing elive email ($random)" ; then
-            # succeed
-            local message_success_sending
-            message_success_sending="$( printf "$( eval_gettext "Email configuration is correctly working: you will find a testing email in your account. You can safely delete it." )" "" )"
+                if echo "$result" | grep -qs "testing elive email ($random)" ; then
+                    # succeed
+                    local message_success_sending
+                    message_success_sending="$( printf "$( eval_gettext "Email configuration is correctly working: you will find a testing email in your account. You can safely delete it." )" "" )"
 
-            if ! { [[ -s "$conf" ]] && grep -qs "email_password=" "$conf" ; } ; then
-                $guitool --info --text="$message_success_sending" || true
+                    if ! { [[ -s "$conf" ]] && grep -qs "email_password=" "$conf" ; } ; then
+                        $guitool --info --text="$message_success_sending" || true
+                    fi
+
+                    # save our conf because we know that it works now
+                    rm -f "$conf" 2>/dev/null
+                    echo "email_account=\"$email_account\"" >> "$conf"
+                    echo "email_password=\"$email_password\"" >> "$conf"
+                    echo "# References that needs to be updated: $HOME/.mutt/accounts/elive-sender" >> "$conf"
+
+                    chmod og-rwx "${conf}"
+
+                    return 0
+                else
+                    sleep 1
+                fi
+
+            done
+            ;;
+        *)
+            if $guitool --question --text="$( eval_gettext "Does the sending of emails work correctly?" )" ; then
+                # save our conf because we know that it works now
+                rm -f "$conf" 2>/dev/null
+                echo "email_account=\"$email_account\"" >> "$conf"
+                echo "email_password=\"$email_password\"" >> "$conf"
+                echo "# References that needs to be updated: $HOME/.mutt/accounts/elive-sender" >> "$conf"
+
+                chmod og-rwx "${conf}"
+
+                $guitool --info --text="$( eval_gettext "Ready! You can start using now the tool" )"
+                return 0
             fi
-
-            # save our conf because we know that it works now
-            rm -f "$conf" 2>/dev/null
-            echo "email_account=\"$email_account\"" >> "$conf"
-            echo "email_password=\"$email_password\"" >> "$conf"
-            echo "# References that needs to be updated: $HOME/.mutt/accounts/elive-sender" >> "$conf"
-
-            chmod og-rwx "${conf}"
-
-            return 0
-        else
-            sleep 1
-        fi
-    done
+            ;;
+    esac
 
 
     # it was correctly configured previously
@@ -459,7 +478,7 @@ do_configure(){
         local message_email_service
         message_email_service="$( printf "$( eval_gettext "Which email provider you want to use?" )" "" )"
 
-        email_account_type="$( echo -e "Gmail\nDreamhost\nother" | $guitool --list --column="Provider" --text="$message_email_service" || echo cancel )"
+        email_account_type="$( echo -e "Gmail\nSMTP\nDreamhost\nother" | $guitool --list --column="Provider" --text="$message_email_service" || echo cancel )"
 
         case "$email_account_type" in
             cancel)
@@ -481,7 +500,7 @@ do_configure(){
 
 
         local message_login
-        message_login="$( printf "$( eval_gettext "Insert your email, for example: %s" )" "john.smith@gmail.com" )"
+        message_login="$( printf "$( eval_gettext "Insert the email to use, for example: %s" )" "john.smith@gmail.com" )"
 
         # request username
         email_account="$( $guitool --entry --text="$message_login" || echo cancel )"
@@ -509,7 +528,7 @@ do_configure(){
     # request password too
     if [[ -z "$email_password" ]] ; then
         local message_password
-        message_password="$( printf "$( eval_gettext "Insert your email password" )" "" )"
+        message_password="$( printf "$( eval_gettext "Insert the email password" )" "" )"
 
         email_password="$( $guitool --entry --text="$message_password" || echo cancel )"
 
@@ -522,6 +541,26 @@ do_configure(){
         fi
     fi
 
+    case "$email_account_type" in
+        SMTP)
+            local message_ask_smtp_url
+            message_ask_smtp_url="$( printf "$( eval_gettext "Insert the URL where for connect to your SMTP." )" "" )"
+            smtp_url="$( $guitool --entry --entry-text="smtp.yourdomain.com" --text="$message_ask_smtp_url" || echo "" )"
+
+            local message_ask_smtp_port
+            message_ask_smtp_port="$( printf "$( eval_gettext "Insert the port to connect to your SMTP. The most common ones are 587, 465, 25." )" "" )"
+            smtp_port="$( $guitool --entry --entry-text="587" --text="$message_ask_smtp_port" || echo "" )"
+
+            local message_ask_imap_url
+            message_ask_imap_url="$( printf "$( eval_gettext "Insert the IMAP address where to connect to check your email." )" "" )"
+            imap_url="$( $guitool --entry --entry-text="mail.yourdomain.com" --text="$message_ask_imap_url" || echo "" )"
+
+            if [[ -z "$smtp_url" ]] || [[ -z "$smtp_port" ]] || [[ -z "$imap_url" ]] ; then
+                $guitool --error --text="$( eval_gettext "Some values are missing. Aborting..." )"
+                exit 1
+            fi
+            ;;
+    esac
 
     # cleanups
     rm -f "$conf"
@@ -550,6 +589,29 @@ do_configure(){
 
             chmod og-rwx "${conf_mutt}"
 
+            ;;
+        SMTP)
+            cat > "${conf_mutt}" << EOF
+# stmp, sending of emails:
+set smtp_url = "smtp://${email_account}@${smtp_url}:${smtp_port}/"
+set smtp_pass = "${email_password}"
+set from = "${USER}@${email_account#*@}"
+set realname = "${USER} from $(hostname) - Elive"
+set copy = no
+set timeout = 120
+
+set imap_user="${email_account}"
+set imap_pass="${email_password}"
+set from="${email_account}"
+set spoolfile=imaps://${imap_url}/
+set folder=imaps://${imap_url}/INBOX/
+set record="=Sent"
+set postponed ="=Drafts"
+set mail_check=60 # So mutt doesn’t keep checking your IMAP folders like a chihuahua with ADHD
+set imap_keepalive = 10 # You may find a small number (like 10) is required to avoid TLS socket packet
+
+set ssl_force_tls=yes
+EOF
             ;;
         Dreamhost)
             cat > "${conf_mutt}" << EOF
